[package]
name = "zed-wit"
version = "0.1.0"
edition = "2024"
rust-version = "1.99"
license = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/chiploom/zed-wit"

[package.metadata.zed-wit]
runtime-lsp-version = "0.1.2"

[lib]
crate-type = ["cdylib", "rlib"]

[workspace]
members = ["crates/wit-syntax", "crates/wit-analysis", "crates/wit-language-server", "crates/xtask", "crates/zed-gui-input"]
default-members = ["."]
resolver = "3"

[dependencies]
zed_extension_api = "=0.7.0"
sha2 = { version = "=0.11.0", default-features = false }

[build-dependencies]
toml = "0.9"

[dev-dependencies]
toml = "0.9"

[profile.release]
lto = "thin"
strip = "debuginfo"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
