[package]
name = "wit-syntax"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false
autobenches = false # Only explicitly listed custom benchmarks are targets.

[dependencies]
tree-sitter = "=0.26.11"
tree-sitter-wit = { git = "https://github.com/bytecodealliance/tree-sitter-wit", rev = "f777cdbe11281ccc68ffa30bd7ea34cdf4ddbec6" }

[dev-dependencies]
serde_json = "1"
toml = "0.9"

[[bench]]
name = "parse"
harness = false
