[package]
name = "wit-syntax"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
tree-sitter = "=0.26.11"
tree-sitter-wit = { git = "https://github.com/bytecodealliance/tree-sitter-wit", rev = "cdf07263b136054b413cab449ac7a1d059c27542" }

[dev-dependencies]
serde_json = "1"
toml = "0.9"
